version: '2.3'

services:
  generative-module:
    build:
      context: ./generative-module-api
      dockerfile: Dockerfile
    image: generative-module
    container_name: generative-module-api
    environment:
      NVIDIA_VISIBLE_DEVICES: "0"
    ports:
      - "7575:80"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./shared:/app/shared
    runtime: nvidia
    networks:
      - generative-cybersecurity-network

  streamlit-module:
    build:
      context: ./streamlit-module-api
      dockerfile: Dockerfile
    image: streamlit-module
    container_name: streamlit-module-api
    ports:
      - "7500:8501"
    volumes:
      - ./shared:/app/shared
    networks:
      - generative-cybersecurity-network

networks:
  generative-cybersecurity-network:
    external: true
