version: '2.3'

services:
  generative-cybersecurity:
    build:
      context: .
      dockerfile: Dockerfile
    image: generative-cybersecurity
    container_name: generative-cybersecurity-container
    environment:
      NVIDIA_VISIBLE_DEVICES: "0"
    ports:
      - "7575:80"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./shared:/app/shared
    runtime: nvidia
    networks:
      - generative-cybersecurity-network

  # streamlit-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: streamlit-app
  #   container_name: streamlit-app-container
  #   environment:
  #     NVIDIA_VISIBLE_DEVICES: "0"
  #   ports:
  #     - "7500:80"
  #   runtime: nvidia
  #   networks:
  #     - generative-cybersecurity-network

networks:
  generative-cybersecurity-network:
    external: true
